package database

// ShopAttemptArtifactPathSQL (migration 0068, docs/SHOP_CUSTOM_RELOCATION.md) widens the attempt
// ledger's artifact_path CHECK from the single legacy location to the legacy location OR the custom/
// location the Nitrado console host actually receives.
//
// Forward-only and additive: every existing row (only the legacy path can exist) stays valid, no row
// is read or rewritten, and the identity trigger from 0054 still makes artifact_path immutable per
// row. 0054 declared the CHECK inline, so its name was generated by PostgreSQL; the constraint is
// found by its definition (a CHECK on this table that mentions artifact_path) rather than by a
// guessed name, then replaced by a NAMED constraint. Re-running is harmless: the replacement is also
// found, dropped and re-added.
const ShopAttemptArtifactPathSQL = `
DO $$
DECLARE c RECORD;
BEGIN
    FOR c IN
        SELECT con.conname
          FROM pg_constraint con
         WHERE con.conrelid = 'shop_delivery_attempts'::regclass
           AND con.contype = 'c'
           AND pg_get_constraintdef(con.oid) LIKE '%artifact_path%'
    LOOP
        EXECUTE format('ALTER TABLE shop_delivery_attempts DROP CONSTRAINT %I', c.conname);
    END LOOP;
END $$;

ALTER TABLE shop_delivery_attempts
    ADD CONSTRAINT shop_delivery_attempts_artifact_path_allowed
    CHECK (artifact_path IN ('champion/champion_shop_delivery.json', 'custom/champion_shop_delivery.json'));
`
