// Package assetstore is Champion's durable object-storage abstraction for customer assets
// (today: faction logos, docs/FACTIONS.md). Feature code depends on Store, never on a
// vendor: the production implementation is PostgreSQL-backed (repository.PostgresAssetStore -
// Champion's only durable storage; the Railway service filesystem is NOT durable and is
// never used for customer assets), and an S3-compatible bucket (Cloudflare R2, a Railway
// Bucket) can implement the same interface later without touching callers or metadata.
package assetstore

import (
	"context"
	"errors"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

// ErrNotFound is returned by Get when no object has the key. Delete is idempotent and
// never returns it.
var ErrNotFound = errors.New("asset not found")

// ErrInvalidKey is returned for a key the store refuses (traversal, odd characters, length).
var ErrInvalidKey = errors.New("invalid asset storage key")

// Store keeps opaque, immutable objects by key. Implementations must be safe for concurrent
// use. Keys are generated by the server; ValidKey is the shared last line of defence.
type Store interface {
	// Put stores data under key, replacing any object with that key.
	Put(ctx context.Context, key, contentType string, data []byte) error
	// Get returns the object's bytes and content type, or ErrNotFound.
	Get(ctx context.Context, key string) (data []byte, contentType string, err error)
	// Delete removes the object. Deleting a missing key is not an error (idempotent).
	Delete(ctx context.Context, key string) error
	// List returns up to limit keys under prefix stored before olderThan, oldest first.
	// It exists for orphan cleanup only.
	List(ctx context.Context, prefix string, olderThan time.Time, limit int) ([]string, error)
	// URL reports a direct public URL for key when the store has one (an S3/R2 public
	// bucket). Stores without one return ("", false) and Champion serves the object itself.
	URL(key string) (string, bool)
}

var keyPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9/._-]*$`)

// MaxKeyLen bounds a storage key.
const MaxKeyLen = 200

// ValidKey reports whether key is a safe storage key: relative, no traversal or empty
// segments, only [A-Za-z0-9/._-], at most MaxKeyLen bytes.
func ValidKey(key string) bool {
	if key == "" || len(key) > MaxKeyLen || !keyPattern.MatchString(key) || strings.Contains(key, "..") || strings.Contains(key, "//") || strings.HasSuffix(key, "/") {
		return false
	}
	return true
}

// MemoryStore is an in-memory Store for tests and local development. It is not durable.
type MemoryStore struct {
	mu      sync.Mutex
	objects map[string]memoryObject
	// PutErr / DeleteErr inject failures in tests.
	PutErr, DeleteErr error
	// Now is the clock used for object timestamps (tests may move it).
	Now func() time.Time
}

type memoryObject struct {
	data        []byte
	contentType string
	at          time.Time
}

func NewMemoryStore() *MemoryStore {
	return &MemoryStore{objects: map[string]memoryObject{}, Now: time.Now}
}

func (m *MemoryStore) Put(_ context.Context, key, contentType string, data []byte) error {
	if !ValidKey(key) {
		return ErrInvalidKey
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.PutErr != nil {
		return m.PutErr
	}
	m.objects[key] = memoryObject{data: append([]byte(nil), data...), contentType: contentType, at: m.Now()}
	return nil
}

func (m *MemoryStore) Get(_ context.Context, key string) ([]byte, string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	o, ok := m.objects[key]
	if !ok {
		return nil, "", ErrNotFound
	}
	return append([]byte(nil), o.data...), o.contentType, nil
}

func (m *MemoryStore) Delete(_ context.Context, key string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.DeleteErr != nil {
		return m.DeleteErr
	}
	delete(m.objects, key)
	return nil
}

func (m *MemoryStore) List(_ context.Context, prefix string, olderThan time.Time, limit int) ([]string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var keys []string
	for k, o := range m.objects {
		if strings.HasPrefix(k, prefix) && o.at.Before(olderThan) {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	if limit > 0 && len(keys) > limit {
		keys = keys[:limit]
	}
	return keys, nil
}

func (m *MemoryStore) URL(string) (string, bool) { return "", false }

// Len reports how many objects are stored (tests).
func (m *MemoryStore) Len() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return len(m.objects)
}

// Has reports whether key is stored (tests).
func (m *MemoryStore) Has(key string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	_, ok := m.objects[key]
	return ok
}

// AgeAll moves every stored object's timestamp back by d (tests: make objects old enough for
// the orphan sweep without waiting).
func (m *MemoryStore) AgeAll(d time.Duration) {
	m.mu.Lock()
	defer m.mu.Unlock()
	for k, o := range m.objects {
		o.at = o.at.Add(-d)
		m.objects[k] = o
	}
}
